### ISSUE TITLE
cauldron-1.7.10-1.1217.01.0 Cauldron-MCPC-Plus version is null

### ISSUE THREAD

**Issue by jamescowens** [MinecraftPortCentral/Cauldron-Issues#1]
Minor issue

cauldron-1.7.10-1.1217.01.0-server.jar when run reports null in the logs for the version number...

[23:06:33 INFO]: This server is running Cauldron-MCPC-Plus version null (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by Sunconure11** [comment]
By any chance, where did you get Cauldron for forge 1217?

**Comment by jamescowens** [comment]
Blood provides early releases for Patreons, of which I am one. He will probably be posting links to the 1217 version when his site is back up. Note that he will be distributing it as a binary patch against a specific build, just like Spigot is doing.

**Comment by Katelyn-SN** [comment]
Do note that public releases of this patch were released on the cauldron website.

**Comment by bloodmc** [comment]
@jamescowens fixed issue, will be included in next update.

**Comment by bloodmc** [comment]
Fixed with commit
https://github.com/MinecraftPortCentral/mcpc-mvn-repo/commit/7c881d0dd64372654804a950586b56f7146e9451

Reinstall your libraries to get latest API.
