### ISSUE TITLE
MFR Slaughterhouse still crashes Cauldron

### ISSUE THREAD

**Issue by aMUSiC** [MinecraftPortCentral/Cauldron-Issues#101]
The 210 build seems to have fixed Grinders, but Slaughterhouses still crash the server.

Placed a slaughterhouse and 37 pigs in a pit. As soon as the slaughterhouse killed a pig it crashed with this stacktrace: http://pastebin.com/Xxr6HcEU

It kept on restarting and crashing (37 times) until every pig was dead.

**Comment by bloodmc** [comment]
Fixed in build 212.
