### ISSUE TITLE
cauldron wont launch with new Cofh

### ISSUE THREAD

**Issue by jules103** [MinecraftPortCentral/Cauldron-Issues#104]
Im running direwolf20 on cauldron, they just updated to 1.0.2 (1.7.10) with a new version of CoFH and it wont start server runs fine when i remove it i hope some1 can help me with this. Really appreciate some help!

CoFH version:
CoFHCore 3.0.0B7-35
CoFHLib 1.0.0B7-29

Heres the error:
http://www.mediafire.com/view/c32d9klaziml3zn/Crashwithcofh.log

**Comment by jules103** [comment]
Issue #92 Is the same problem just let them know that it is CoFH that wont run on this version

**Comment by bloodmc** [comment]
dupe #92
