### ISSUE TITLE
10000 packets/s sent from the server

### ISSUE THREAD

**Issue by MuresanSergiu** [MinecraftPortCentral/Cauldron-Issues#106]
So I'm getting about 10000 packets/s sent for no apparent reason the packet that is sent is S35PacketUpdateTileEntity. I'm getting about 1-2 MB/s uploaded to the server, which is a huge amount of data. Since there's no apparent mod causing it I'm gonna post it here just in case it's actually from cauldron itself.
Here's the Opis screen, showing that.
![bug](https://cloud.githubusercontent.com/assets/5781599/5158748/5aa85e8a-7351-11e4-961e-1fe7c60074d8.png)
Using build 212 and these mods:
https://docs.google.com/spreadsheets/d/1j2xfgkPB7enscejgbmpZkBsKKR0lMioVRHOMfXkvG6g/edit#gid=1

**Comment by bloodmc** [comment]
@AfterWind Did you do the same test with Forge only?

**Comment by MuresanSergiu** [comment]
Not yet, atm I'm testing to see if it's just one of the mods. Just wanted to know if there's a way cauldron could cause this weird issue.

**Comment by MuresanSergiu** [comment]
Yup, it's not cauldron, is there any utility I can use to analyze the traffic between the server and the client?

**Comment by Slind14** [comment]
Check outbound 250
