### ISSUE TITLE
Dupe bug with plants dynamics

### ISSUE THREAD

**Issue by deepvelocity** [MinecraftPortCentral/Cauldron-Issues#108]
For example if you plant  a sugar cane and remove water source from it, the cane will stay. But if you change a block next to it afterwards, it will be destroyed. 
It causes a strange dupe bug inside protected areas (WorldGuard, Factions): a player places a wooden door inside the single water source block near the cane and then the cane item is dropped, but the cane block does not disappear (due to the fact that the door wasn't placed at all?)

**Comment by bloodmc** [comment]
@KawaiiDesu You need to provide more info, sadly I am not a magician. What build of Cauldron are you using? Have you tested this issue without any plugins or mods?

**Comment by deepvelocity** [comment]
@bloodmc Cauldron build is the latest one (1.1236.05.212).
As I have mentioned, the dupe bug can be used only with protecton plugins like WG.
The bug with dynamics is confirmed to work without mods/plugins.
I can provide a video or an image guide on the issue.
