### ISSUE TITLE
[1.7.10, forge 1217] Ghost mobs spawning upon player death

### ISSUE THREAD

**Issue by Brycey92** [MinecraftPortCentral/Cauldron-Issues#11]
In a clean cauldron server running forge 1217, upon player death, mobs spawn at an increased rate all around the player, and do not move. The mobs exist client-side, but the problem does not exist in singleplayer, or on a forge-only server. Other users cannot see the mobs, and /butcher and /stoplag do not stop or prevent the problem. The spawning continues until the user's fps is 0 and all available memory is used. All "ghost" mobs disappear when the user clicks "Respawn."

Server software used:
Maeyanie's Cauldron 1.7.10 198 server installer
CauldronInstallerPatch-1.1217.01.205
SpigotPatcher
*Tested using a server with mods/plugins, and also tested with no mods/plugins
*Tested against a clean forge 10.13.1.1217 server, where the issue was not present

Client forge versions tested:
10.13.1.1223
10.13.1.1219
10.13.1.1217
10.13.0.1180
*Tested using mods, and also tested with no mods

Server and client operating systems:
Windows 7 Ultimate x64

Java version:
1.7.0_67 x64

Error messages:
None upon event on client or server

Logs:
https://gist.github.com/Brycey92/3e46e22cf43cf1ba9d6e
https://gist.github.com/Brycey92/9233aaf20f714d07d2f2
https://gist.github.com/Brycey92/77f9d5ce4b31c84ab8cc
https://gist.github.com/Brycey92/acad8a679305f5f6efcc

Steps to reproduce:
Install forge onto a minecraft client. The versions listed above have been tested, but other versions may also reproduce the issue. Install a cauldron 1.7.10 1217 server. The client and server do not need to have any mods or plugins, but having them present does not affect the issue. A minimap with mobradar may help you see the mobs spawning around you. Use any difficulty except peaceful. Connect to the server and die in some way that you can see where mobs would spawn. (Not underwater or looking up or down, and not facing a wall.) If you die at night, more mobs spawn, such as hostile ones, and the effect of the issue is more visible. Wait a few seconds, and you should start to see small groups of mobs spawning at an increased rate. If you leave the game in this state, your fps will decrease and memory used will increase as more ghost mobs spawn. Running /difficulty 0 on the server will stop new ghost mobs from spawning, but will not affect existing ones. When you click "Respawn," all ghost mobs will disappear. I have noticed that, after respawn, mobs flash in and out of existence around you for a period of time, although I have not tested the effect that respawning in a different area has on these flashing mobs. In the same client session, and different sessions, the issue is not present in singleplayer or on a forge-only server.

Expected result:
Mob spawning should continue normally after death and before respawn.

Actual result:
The above issue happens.

Previous builds:
I did not notice the issue when I was using cauldron 1.7.10 1207, but I have not explicitly tested it.

Screenshots:
(The final 2 are from the latest test, which is also the source of the logs.)
![](http://puu.sh/c5XXz/671635cc6f.png)
![](http://puu.sh/c6stx/46c293a194.png)
![](http://puu.sh/c6sEz/02a109ed92.png)
![](http://puu.sh/c71QR/957c070ed5.png)
![](http://puu.sh/c7jPO/8ff378b6c2.png)

Thanks for taking the time to read this issue report! If you need anything else, please let me know.

**Comment by bloodmc** [comment]
@Brycey92 Reproduced issue, thanks. Will fix soon.

**Comment by bloodmc** [comment]
@Brycey92 
This issue is related to our despawn-immediate feature. Since you are the only player on server, every single entity despawned when you die forcing them to start spawning around you. As a temporary workaround, simply change the following setting to false in your cauldron.yml

   entities:
      despawn-immediate: false

I may end up just removing this feature entirely as it can cause more problems than help. We shall see =)

**Comment by Brycey92** [comment]
Thanks for the help! Should I close this issue, or wait for a more permanent fix?

**Comment by Brycey92** [comment]
Note to anyone else reading this: The issue has been fixed in CauldronInstallerPatch-1.1231.01.206. Blood changed entity-despawn-immediate to be disabled by default.
