### ISSUE TITLE
Cant update my server

### ISSUE THREAD

**Issue by rapidfanatics** [MinecraftPortCentral/Cauldron-Issues#126]

**Comment by spannerman79** [comment]
log files?  more details?

**Comment by vico93** [comment]
If your issue is related to Yive's Mirror things, please ask in comments box there.

**Comment by rapidfanatics** [comment]
Well it was about a bug but i do have a problem with Yive's download because they don't have cauldron for 1291, i know people that have it are being selfish but there has to be someone willing to give it out as only large servers have it so far causing smaller servers to close down and they get even more players.

**Comment by vico93** [comment]
Last time i checked the Yive's mirror, not only they have a copy of 1291 jar but also have updataed copies up to 1381.

**Comment by spannerman79** [comment]
@vpontin within the zip its ready to go (extract etc) or do i need to perform a bps patch thats included within the zip? http://tcpr.ca/info/cauldron/cauldron-1.7.10-1.1381.06.221.zip
