### ISSUE TITLE
(#65) Cauldron Server crash with CoFH Core installed - still happening with latest version

### ISSUE THREAD

**Issue by Thornbush42** [MinecraftPortCentral/Cauldron-Issues#136]
The title says it all

Minecraft 1.7.10; CoFH Core 3.0.0B9-40

No crash log was created, so this is directly copied from the server: http://pastebin.com/zccwR7dp

**Comment by thormbush42** [comment]
This is due to ASM5 library not being installed - Resolved

**Comment by Thornbush42** [comment]
This is due to ASM5 library not being installed - Resolved
