### ISSUE TITLE
Cauldron Server Not Working When Mods Added

### ISSUE THREAD

**Issue by Akarm2000** [MinecraftPortCentral/Cauldron-Issues#138]
My cauldron server works perfectly fine without mods, but when i drop in the crackpack mods it stops working. Please let me know why. 

run.bat file:
java -XX:PermSize=3G -XX:MaxPermSize=5G -Xmx6G -Xms3G -jar cauldron.jar 
PAUSE

Crash Log:
http://pastebin.com/37ggCvHb

**Comment by Thornbush42** [comment]
The crash report states "Duplicate enchantment id" so perhaps by changing the enchantment ids in thormcraft's config the problem may be fixed - not a cauldron issue here

**Comment by Akarm2000** [comment]
I looked through the thaumcraft config and no ids are the same, is it conflicting with itself or another mod?

**Comment by Akarm2000** [comment]
Okay so i changed the item ids and now i get this error,

http://pastebin.com/fuD6cUCD

**Comment by Akarm2000** [comment]
It says that the two mods, flaxbeard and thaumic wxploration.class enchantment binding.

**Comment by Akarm2000** [comment]
New crash log :D
http://pastebin.com/rKGfuSww
Have i fixed the conflicting problem?

**Comment by MuresanSergiu** [comment]
Nope, I believe you changed the id to 7777, which might be out of bounds. Not sure what the bounds are for that array but I suggest trying something smaller.

**Comment by Akarm2000** [comment]
WIll do
i changed it to 400 and something but now i get this problem
http://pastebin.com/rN5cxWFx

**Comment by MuresanSergiu** [comment]
I don't think you have changed it though xD

**Comment by Akarm2000** [comment]
the enchantment binding?

**Comment by Akarm2000** [comment]
do you have skype, it would be much faster and i could screen share

**Comment by MuresanSergiu** [comment]
I don't think I would be of much help as I haven't encountered this issue before. I was suggesting that you change that enchantement ID to something lower. That's all I know.

**Comment by Akarm2000** [comment]
Its on 465

**Comment by Akarm2000** [comment]
do you yourself have a cauldron server?

**Comment by Akarm2000** [comment]
why does it have to be so hard

**Comment by MuresanSergiu** [comment]
I think if you disable either mariculture or thaumic exploration it should work.

**Comment by Akarm2000** [comment]
ok
ill try

**Comment by Akarm2000** [comment]
im still getting errors

**Comment by Akarm2000** [comment]
i fixed it mostly, when i dropped the mods into the cauldron server i neweded to put in teh changed config from it too instead of it generating its own.
Last problem now though
![image](https://cloud.githubusercontent.com/assets/11358453/6541469/ac051e38-c4ca-11e4-82be-9b1b1c3a639e.png)

**Comment by Akarm2000** [comment]
do i just drag and drop in these mod rejections or something?

**Comment by Akarm2000** [comment]
i messed up, id ragged in the config but not the mods, damn i thought i had it XD

**Comment by Akarm2000** [comment]
and its broken again XD

**Comment by Akarm2000** [comment]
anyone here have skype so they can give a quick walkthrough and get this over with?

**Comment by Akarm2000** [comment]
The server works, i just installed the new config and mods and its fine now. 
Thanks for all of your help.
Have a nice day :D
