### ISSUE TITLE
Cauldron Server Keeps Pausing

### ISSUE THREAD

**Issue by Akarm2000** [MinecraftPortCentral/Cauldron-Issues#139]
So my server crashed cause my computer crashed and because of that when i run my server it Pauses straight away.
http://pastebin.com/TYwHxG8S

**Comment by Thornbush42** [comment]
There's a required mod missing in your server setup which another mod needs to run.

Sent from my Windows Phone

**Comment by Akarm2000** [comment]
and which mod is that?

**Comment by Thornbush42** [comment]
The crash does not say which mod it is, you will have to find that yourself

Sent from my Windows Phone

**Comment by Akarm2000** [comment]
uuuuuuuuuuuuuuh

**Comment by Akarm2000** [comment]
u sure this is the problem?

**Comment by Thornbush42** [comment]
The error states "cpu.mods.fml.MissingModsException" so yeah

Sent from my Windows Phone

**Comment by Akarm2000** [comment]
ive just replace all of the mods and config files but it is still doing it.
http://pastebin.com/VQwYn5pr

**Comment by Thornbush42** [comment]
Try creating a fresh cauldron server and placing the mods & configs in

Sent from my Windows Phone

**Comment by Akarm2000** [comment]
i dont remember how i did it

**Comment by Thornbush42** [comment]
Please can you paste the "latest.log" into pastebin for me - located in the "logs" folder

**Comment by Akarm2000** [comment]
http://pastebin.com/PxR8V4eE

**Comment by Thornbush42** [comment]
To fix this problem you need to update Cauldron, or rather the version of Forge that comes with Cauldron. To do this you need to download an updated version of cauldron.

Download the top option on this page (cauldron-1.7.10-1.1307.06.218.zip): http://tcpr.ca/cauldron
Download the Minecraft server (click on "server jar" next to 1.7.10): https://mcversions.net/
Download the "Run.bat" file: https://www.dropbox.com/s/0oeaibkljpe2okx/Run.bat?dl=0

Extract the contents of "cauldron-1.7.10-1.1307.06.218.zip" to a new folder and place the "minecraft-server.1.7.10.jar" into the same folder. Then double-click on the "cauldron-1.7.10-1.1307.06.218.jar" file. Then place the "Run.bat" file into the same new folder.
You may now add any mods and configs you wish, followed by opening the "Run.bat" file.

Remember to agree to EULA in the "eula.txt" if you encounter problems.

**Comment by Akarm2000** [comment]
when i double click the cauldron file nothing happens

**Comment by Akarm2000** [comment]
you mean minecraft file?

**Comment by Akarm2000** [comment]
ok so
i downloaded the things
installed a normal minecraft server
dragged the minecraft files from the jar into the cauldron jar#
ran the bat and now im getting this problem.

**Comment by Akarm2000** [comment]
it still pauses straight away

**Comment by Akarm2000** [comment]
hallp

**Comment by Akarm2000** [comment]
![image](https://cloud.githubusercontent.com/assets/11358453/6547113/9a480564-c5c6-11e4-8f84-d56fb575ff43.png)

**Comment by Akarm2000** [comment]
there is no crash folder so this is what i resorted to

**Comment by Thornbush42** [comment]
Nothing is supposed to happen when you double click the cauldron server jar.
Check that you:
A) Created a new folder, called "New Server" for example.
B) put all the files from the "cauldron-1.7.10-1.1307.06.218.zip" into the "New Server" folder,
C) put the "minecraft-server.1.7.10.jar" into the "New Server" folder,
D) put the "Run.bat" into the "New Server" folder,
E) double-clicked on the "cauldron-1.7.10-1.1307.06.218-server.jar" (expect nothing to happen)
F) put the mods & configs in the correct directory
G) accepted the EULA in the "eula.txt" - change the "false" value in the file to "true"

**Comment by Akarm2000** [comment]
open the cauldron server in winrar and drag them in ur just drag the jar file?
sorry if i said nooby
1. i am
2. wanna get this over witjh XD

**Comment by Thornbush42** [comment]
Yeah, open the "cauldron-1.7.10-1.1307.06.218.zip" in a program, like WinRAR, and drag ALL files into the "New Server" folder

**Comment by Akarm2000** [comment]
the cauldron.jar and libraries or in that cauldron.jar?

**Comment by Thornbush42** [comment]
drag BOTH the ".jar" and the libraries folder into the "New Server" folder

**Comment by Akarm2000** [comment]
Yeah, the server works.
One last thing, when i launch the .bat file it makes me type in my administrator password
Is there a way of stopping that?

**Comment by Thornbush42** [comment]
Not with the current Cauldron version, no. Also, if it's fixed can you please mark this report as closed, thanks.

**Comment by Akarm2000** [comment]
Thanks for all of the help. :D
