### ISSUE TITLE
This message comes up and closes RIGHT AWAY(Got a quick screenshot luckily)

### ISSUE THREAD

**Issue by jonetiz** [MinecraftPortCentral/Cauldron-Issues#148]
As the title says. I dont have ANY mods yet, and this happens.
![bandicam 2015-03-22 00-29-06-210](https://cloud.githubusercontent.com/assets/5671812/6768511/a4640550-d02c-11e4-83b4-c544e70a2024.jpg)

**Comment by jonetiz** [comment]
Ok, I run it as admin, everything comes up, but instead of the errors it says Error: Unable to access jarfile cauldron.jar

**Comment by vico93** [comment]
Cauldron isn't anymore maintained by a central team (used to be bloodmc).
Now some server owners with some java knowledge are updating Cauldron for their own. Some lock the updates for ourselves, while others (benevolents) release that for a guy/girl called 'Yive';
Check its Twitter @ItsYive to ask about his repository and (possibly) for Cauldron updates. This repository is dead.
Sincerely...
