### ISSUE TITLE
Chat Format not working?

### ISSUE THREAD

**Issue by Time6628** [MinecraftPortCentral/Cauldron-Issues#149]
I'm running a NaturalMagic 0.0.8 server. I have WorldEdit, ItemRestrict, SimpleAutoMessage, OpenInv, Vault, ClearLag, PermissionsEx, GriefPrevention, AutoSaveWorld, Votifier, Prism, WorldGuard, GAListener, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat, and EnjinMinecraftPlugin installed. Yet, the chat doesn't format to what I have set to in the configs. Any ideas?
Thanks,
- Time

**Comment by Thornbush42** [comment]
Try updating the chat plugin(s) to their latest version

Sent from my Windows Phone

**Comment by Time6628** [comment]
I am running the latest official version of essentials chat. I've also tried several other chat plugins. :/

**Comment by Thornbush42** [comment]
What version of Minecraft are you running the server on?

Sent from my Windows Phone

**Comment by Time6628** [comment]
1.7.10

**Comment by Time6628** [comment]
cauldron-1.1236.05.211
