### ISSUE TITLE
TerraFirmaCraft entities are not knock-backing on damage

### ISSUE THREAD

**Issue by Polyana-Fontes** [MinecraftPortCentral/Cauldron-Issues#15]
The entities are not knock-backing and not showing any damage effect when they receive damage (with exception of zombie). This includes player entities.

This only occurs in cauldron servers even without plugins and without other mods.

Cauldron version: 1.7.10-1.1217.01.0
TerraFirmaCraft version: 0.79.6.245
http://terrafirmacraft.com/download.html

Video Demonstration:
http://youtu.be/_HJf27F_RWw?t=1m3s (i had some client mods installed but the server had only TerraFirmaCraft)
Server log of the video demonstration: http://pastebin.com/3eyeY1wk

**Comment by azenin** [comment]
I got this problem too. Also, damage taken from falling, burning, drowning and suffocating lowers hp only by 1-10 hp (default full hp bar in TerraFirmaCraft =1000 hp)

**Comment by Azaysol** [comment]
another issue is that animals are not dropping any loot which is vital to survival.
linking back to forum post in cauldron, now listed under issue #30 

http://cauldron.minecraftforge.net/threads/tfc-79-6-issues-with-patched-cauldron.498/

**Comment by Polyana-Fontes** [comment]
This is still happening on TerraFirmaCraft 0.79.7.292

I also noticed that explosion and fall damages are taking are too low and is making the player basically invulnerable to that kind of damages.

**Comment by azenin** [comment]
As I can see the solution must be simple: you need to calculate damage taken in relative quantities not in absolute ones. When drowning, falling etc. it takes 0.5-3 hp in vanilla healthpoints, but TFC healthbar has 1000 hp by default and max hp can be changed in game by consuming different types of food, level up and etc. So you need to recalculate damage: e.g. drowning taking a half of vanilla heart per act, its equals 0.5/10 = 5% of max heath, then you need to took off 5% of TFC current max health, 5% of 1000, for example, = 50 TFC hp.

**Comment by Azaysol** [comment]
Alek while what you say is true, i dont see why cauldron would have changed the way that is calculated. Its not like TFC has these issues with Forge so not sure why Cauldron would re-edit those calculations. Also can we get some sort of update here...

**Comment by Azaysol** [comment]
the new bps patch did not fix any of the issues

**Comment by Obatunde** [comment]
I have the same problem running Cauldron-1.1231.01.207  with [1.7.10]TerraFirmaCraft-0.79.8.328

So far we have  mobs not dropping items. and not knocking back also fall damage is wrong.
Any help is appreciated.

**Comment by Azaysol** [comment]
its not just fall damage btw, fire damage and drowning damage as well. Basically all forms of damage not inflicted by a mob is being done as vanilla damage. there are also no logs to post as no errors show up

**Comment by Azaysol** [comment]
someone asked me to add more info in irc:
this is running java 7update 67 also tried with 71, on windows and linux machines.
there are no error logs to report because the server does not crash or see any issues.
in cauldron 1.6.4 and tfc 1.6.4 this used to work fine

**Comment by Brycey92** [comment]
Aldo1028 also tested with normal forge, where the issue was not present.

**Comment by bloodmc** [comment]
Finally got some time today to check this bug out. It has been fixed and will be released in next update =). The problem was how I was handling Forge's LivingHurtEvent.

**Comment by azenin** [comment]
Thank you very much, blood! But please, note, that TFC runs on .1217 Forge only so it would be perfect if you update corresponding patch.

**Comment by bloodmc** [comment]
@aleksandrzenin If it ONLY works on Forge 1217 and not 1231+ you need to tell them to fix it because I'm not updating for older forge builds.

**Comment by azenin** [comment]
@bloodmc TFC devs focused on this 1217 forge build http://terrafirmacraft.com/f/topic/6932-796-cauldron-compatibility/#entry95874, could you please update this patch http://cauldron.minecraftforge.net/threads/cauldroninstallerpatch-1-1217-01-205.489/ ?

**Comment by bloodmc** [comment]
No it will only support 1231+

**Comment by Azaysol** [comment]
Blood dont worry about it, thanks for the update. It will work fine

**Comment by bloodmc** [comment]
Fixed in build 208.
