### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by TerdyTheTerd** [MinecraftPortCentral/Cauldron-Issues#161]
So this little bug has been around on my server forever, I don't want to say this it is cauldrons fault per se becuase more than likely it is some mod conflict. The issue here is that whenever anything in chat that is directed towards specific players(like chat, or listings warps/home/commands) there is an extra prefix infron of all of it which happens to be "======". The weird part is that this is only client side and in the server console the "======" doesn't appear. I'm more asking if anyone has maybe some info on this or possible workarounds, heres and example. 
![bug](https://cloud.githubusercontent.com/assets/9743432/8611199/dfe563e2-2682-11e5-93d8-647a0375d69c.png)

Its not a world prefix from multiverse because I don't have mutliverse, and the only chat related plugins are essentials and factions, but its really not a huge problem.

**Comment by vico93** [comment]
This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!

**Comment by spannerman79** [comment]
For the record this wasn't a kCauldron issue but a mod issue due to language files or something along those lines.

**Comment by TerdyTheTerd** [comment]
Ya I posted it along with the fix for it in the KCauldron github thing, turns out it was a bad compile of a pull request merge ina  mod, causing redudant lines in the lang files, in which git added some lines like ====== to show the duplicate lines which cauldron ready as a prefix :/, just glad its fixed
