### ISSUE TITLE
Cauldron website is down

### ISSUE THREAD

**Issue by Sunconure11** [MinecraftPortCentral/Cauldron-Issues#2]
I cannot access the cauldron website. Did it change, or is it just down?

**Comment by bloodmc** [comment]
I'm waiting for @OvermindDL1 to update the DNS entry for Cauldron's website since the IP address changed. Once that is done, it will be back up.

**Comment by Sunconure11** [comment]
Where are people getting the newer versions of Cauldron?

**Comment by bloodmc** [comment]
Website is up. Downloads can be found on website.
