### ISSUE TITLE
Duplicate Handler // BungeeCord

### ISSUE THREAD

**Issue by Beelzaboss** [MinecraftPortCentral/Cauldron-Issues#20]
Hi guys,

I have a problem with OpenLib (Lib for Open Blocks) that is conflicting with Bungeecord // Cauldron.

Server Error: http://pastebin.com/GSKuN4E4
Client Crash: http://pastebin.com/YJt5RT4D

Open Blocks Issue: OpenMods/OpenBlocks#498
Open Lib Issue: OpenMods/OpenModsLib#21

Thanks for the help in advance, Greatly appreciated.

**Comment by bloodmc** [comment]
Post a COMPLETE server log, not a partial one.

**Comment by Beelzaboss** [comment]
Here is my full server log at that time,

Full server log: http://197.189.226.50/FullServerLog.txt

**Comment by boq** [comment]
Hi, OpenMods dev here. Logs probably won't help. I analyzed issue and found possible cause, description in this issue: SpigotMC/BungeeCord#1248. It's probably not Cauldron issue, unless something explicitly changes order of handshake messages (specifically, channel list on `REGISTER` channel).

**Comment by devryb** [comment]
Same issue here

**Comment by dualspiral** [comment]
BungeeCord issue - will be fixed when https://github.com/SpigotMC/BungeeCord/pull/1256 is pulled.

**Comment by bloodmc** [comment]
@dualspiral Thanks.
