### ISSUE TITLE
Cauldron Crash

### ISSUE THREAD

**Issue by coolotter103000** [MinecraftPortCentral/Cauldron-Issues#21]
I try to start the server with <code>java -Xmx1024M -Xms1024M -jar cauldron.jar
pause </code>
But a crash comes and this is the crash
<code>7:34:26 PM [warning] 19:34:26,357 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
7:34:26 PM [warning] 19:34:26,359 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
7:34:30 PM [javastacktrace] A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
7:34:30 PM [javastacktrace]     at java.lang.reflect.Method.invoke(Unknown Source)
7:34:30 PM [javastacktrace]     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
</code>
And i am using Bukkit GUI And i got screen shot of console withour Bukkit GUI
![image](https://cloud.githubusercontent.com/assets/6482795/4691756/0022bee2-5731-11e4-915f-6c31aa000e40.png)

**Comment by bloodmc** [comment]
You need to run the installer, follow directions here http://cauldron.minecraftforge.net/wiki/primer-for-cauldron-and-forge/
