### ISSUE TITLE
"NEI server config" Crash when starting up

### ISSUE THREAD

**Issue by BBoldt** [MinecraftPortCentral/Cauldron-Issues#24]
cauldron-1.7.10-1.1217.01.0-server.jar
NotEnoughItems-1.7.10-1.0.3.62-universal

Not sure what the hell I did this time. It's possible I deleted a config file.

Anyways, this crash happens when starting up the server:

http://pastebin.com/FLNxLnzV

Doesn't happen with regular forge server.

I know there is a newer version of Cauldron, but I haven't updated all my mods to Forge 1231 compatible yet so I haven't tested it. Apologies if this is already fixed there.

**Comment by BBoldt** [comment]
Yes, still having this problem in 1231:
http://pastebin.com/MHDmxRvY

**Comment by bloodmc** [comment]
Dupe #7
