### ISSUE TITLE
Build 206 | Sapling dont grow naturally

### ISSUE THREAD

**Issue by F4ith93** [MinecraftPortCentral/Cauldron-Issues#25]
Hey,

after updating to Build 206, the Users and We recognize that Sapling will not grow
naturally anymore.

The Member Whist34 on http://cauldron.minecraftforge.net/ tested it out:
http://cauldron.minecraftforge.net/threads/cauldroninstallerpatch-1-1231-01-206.527/#post-2913

Greets

**Comment by bloodmc** [comment]
Fixed in build 207.
