### ISSUE TITLE
MultiInv can't change player Inventories

### ISSUE THREAD

**Issue by leeci** [MinecraftPortCentral/Cauldron-Issues#27]
MultiInv is work fine in Cauldron 1.7.2-1.1147.04.196 and Spigot 1.7.10-R0.1. But when I use in Cauldron 1.7.10. Only can change SURVIVAL and CREATIVE inventories. When I switch different world. The Inventories doesn't be changed.

Server log:http://pastebin.com/EwGFZB2h
MultiInv:http://dev.bukkit.org/bukkit-plugins/multiinv/

Thanks for the help.

**Comment by bloodmc** [comment]
"If MultiInv refuses to work and you can't change inventories, it's because you have the wrong version of the TuxTwoLib!"

**Comment by bloodmc** [comment]
There may have been a bug on my end, grab build 209.
