### ISSUE TITLE
1207.01.195 to the 1217 or the 1231 Crash on World Load

### ISSUE THREAD

**Issue by xF4m3** [MinecraftPortCentral/Cauldron-Issues#28]
I got a problem updating from an older cauldron version 1.1207.01.195 to the 1217 or the 1231
the crash report say's something about multiparts, but I can't get more out of that report.
would be nice If we could be able to fix this, only happens with our old world, the server does start with a completly new wold, but not with our old one 

[SPOILER="Crash Report"]
[CODE]---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
Time: 10/20/14 6:13 PM
Description: Exception in server tick loop
java.lang.VerifyError: Illegal type at constant pool entry 31 in class codechicken.multipart.scalatraits.TPartialOcclusionTile$class
Exception Details:
  Location:
    codechicken/multipart/scalatraits/TPartialOcclusionTile$class.occlusionTest(Lcodechicken/multipart/scalatraits/TPartialOcclusionTile;Lscala/collection/Seq;Lcodechicken/multipart/TMultiPart;)Z @24: invokeinterface
  Reason:
    Constant pool index 31 is invalid
  Bytecode:
    0000000: 2cc1 0009 9900 1e2a 2b2c b200 0fb6 0013
    0000010: b900 1903 00c0 0015 b900 1f02 009a 0005
    0000020: 03ac 2a2b 2cb9 0023 0300 ac  
  Stackmap Table:
    same_frame(@34)
    at TileMultipart_cmp$$22.<init>(Unknown Source)
    at TileMultipart_gen$$23.generate(Unknown Source)
    at codechicken.multipart.asm.ASMMixinFactory$SuperSet.generate(ASMMixinFactory.scala:60)
    at codechicken.multipart.asm.ASMMixinFactory$.generateTile(ASMMixinFactory.scala:310)
    at codechicken.multipart.MultipartGenerator$.generateCompositeTile(MultipartGenerator.scala:124)
    at codechicken.multipart.TileMultipart$.createFromNBT(TileMultipart.scala:678)
    at codechicken.multipart.handler.MultipartSaveLoad$.loadTiles(MultipartSaveLoad.scala:64)
    at codechicken.multipart.handler.MultipartEventHandler$.tileEntityLoad(MultipartEventHandler.scala:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_552_MultipartEventHandler$_tileEntityLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:469)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.2.0-4-amd64
    Java Version: 1.7.0_72, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 5014671872 bytes (4782 MB) / 6372720640 bytes (6077 MB) up to 14962655232 bytes (14269 MB)
    JVM Flags: 5 total; -Xincgc -Xms6G -Xmx14G -XX:PermSize=1G -XX:ParallelGCThreads=8
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 62, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.85.1231 Minecraft Forge 10.13.2.1231 106 mods loaded, 106 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{7.10.85.1231} [Forge Mod Loader](cauldron-1.7.10-1.1231.01.206-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{10.13.2.1231} [Minecraft Forge](cauldron-1.7.10-1.1231.01.206-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems{1.0.3.62} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2{2.2.650-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.650-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BiblioCraft{1.7.5} [BiblioCraft](BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.993-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forestry{3.1.0.3} [Forestry for Minecraft](forestry_1.7.10-3.1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AWWayofTime{v1.2.0} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CarpentersBlocks{3.3.0} [Carpenter's Blocks](Carpenter's Blocks v3.3.0 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ImmibisCore{59.0.3} [Immibis Core](immibis-core-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    DimensionalAnchors{59.0.2} [Dimensional Anchors](dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Thaumcraft{4.2.0.0} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TConstruct{1.7.10-1.7.0.build702} [Tinkers' Construct](TConstruct-1.7.10-1.7.0d3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ForgeMultipart{1.1.0.307} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThaumicTinkerer{2.5-1.7.10-155} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-155.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MagicBees{1.7.10-2.1.21} [Magic Bees](magicbees-1.7.10-2.1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderIO{1.7.10-2.1.0.223} [Ender IO](EnderIO-1.7.10-2.1.0.223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    enhancedportals{3.0.7} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12bnull.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FoodPlus{3.2rS} [§bFood Plus](FoodPlus-1.7.x-3.2rS.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WaslieCore{1.1} [WaslieCore](WaslieCore-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ForestryExtras{3.1} [Forestry Extras](ForestryExtras-2-3.1_B24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraveStone{2.9.7} [GraveStone](GraveStone 2.9.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    gregtech{MC1710} [GregTech](gregtech_1.7.10-5.05.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    HardcoreEnderExpansion{1.6.4} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2NuclearControl{1.7.10.06} [Nuclear Control](ic2nc-1.7.10-1.7.10.06.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    InfernalMobs{1.5.7} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IronChest{6.0.41.729} [Iron Chest](ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineTweaker3{3.0.9} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ModTweaker{0.6} [ModTweaker](ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Morpheus{1.7.10-1.5.24} [Morpheus](Morpheus-1.7.10-1.5.24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-226.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore](OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenPeripheral{0.2.0} [OpenPeripheralAddons](OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-437.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenComponents{0.2.0.21} [OpenComponents](OpenComponents-MC1.7.10-0.2.0.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OpenComputers{1.3.6.69} [OpenComputers](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    fodc{1.5.2} [Ore Dictionary Converter](OreDictionaryConverter-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    planetguyLib{1.0} [planetguyLib](PlanetguyLib-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PneumaticCraft{1.2.11-26} [PneumaticCraft](PneumaticCraft-1.7.10-1.2.11-26-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RandomThings{2.1.5} [Random Things](RandomThings-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RotaryCraft{Gamma} [RotaryCraft](RotaryCraft 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ReactorCraft{beta} [ReactorCraft](ReactorCraft 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    JAKJ_RedstoneInMotion{2.1.3} [Remain In Motion](RemainInMotion-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    JAKJ_RedstoneInMotion_HollowCarriages{1.0} [JAKJ_RedstoneInMotion_HollowCarriages](RemainInMotion-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesWorkshop{0.5.1} [Steve's Workshop](StevesWorkshop-0.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TiCTooltips{1.1.9} [TiC Tooltips](TiC-Tooltips-mc1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    UndergroundBiomes{0.6h} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.6h13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    McMultipart{1.1.0.307} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ForgeMicroblock{1.1.0.307} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Bukkit, MCPC+, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: IC2:ON, RotaryCraft:ON, RC:ON, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)[/CODE]
[/SPOILER]

**Comment by McyD** [comment]
Try updating Multipart, I am running Multipart .311 with no issue.

**Comment by xF4m3** [comment]
Yeah thank you that seems to be working :) thank you very much :+1:

**Comment by bloodmc** [comment]
@McyD Thanks
