### ISSUE TITLE
Plugins not loading, crashes upon /help

### ISSUE THREAD

**Issue by TimB1087** [MinecraftPortCentral/Cauldron-Issues#3]
Using Cauldron 1217. Server loads fine, however plugins don't load. When trying to use /help or /?, server shuts down without crash reports. Can't catch console quick enough to grab info from it.

I confirmed that no plugins are actually loaded, since things like permissions, essentials warping or chat formatting are not working.

**Comment by jburrows82** [comment]
Is this on a new installation?

**Comment by TimB1087** [comment]
I patched using the latest 1217 bps and ran the server installer on my desktop to generate the libraries and two .jars, then uploaded all of the files to my server. Of course, I did remove all the old cauldron libraries and jars off of my server beforehand, ensuring that what uploaded were new files and not overwrites.

There seems to be some quirks when running the installer, and now my my console is giving me missing library issues. Seems the installer doesn't always install all the libraries. Still troubleshooting on my end.

**Comment by TimB1087** [comment]
Resolved the issue. The error seems to have originated simply from the installer not properly installing all required files. I would recommend, for now, informing people that they may have to run the installer multiple times to get a proper file generation. I would also recommend a checksum or some other way for people to verify their installation was successful.

The first issue I ran into was plugins not loading and server crashing when trying to invoke plugin commands. This was produced on my first Cauldron 1217 installation, which was missing some libraries.

The second issue was the server not starting due to missing libraries, which was happening when I re-ran the installer and replaced only the libraries.

The issue was resolved when I ran the installer a third time, deleted ALL Cauldron related files in my server, and dropped the new installed files into the server, including the newly generated jars.

No other changes beyond this were made. Simply a cauldron installer issue it seems like.

**Comment by bloodmc** [comment]
Not a cauldron issue at all. Many libs changed with Forge 1217 update and you most likely ran the installer on TOP of existing libs which is a bad idea. Whenever Forge upgrades to a new version, you should always wipe out your libs and reinstall before running the installer. If this happened with a FRESH install, then it is a problem on my end.

**Comment by TimB1087** [comment]
It did happen with a fresh install. I installed this to a new folder on my desktop before copying over to my server via FTP. The first installation was indeed missing several libs. Running the installer again, in a new folder, installed all the libraries. I also, each time, ensured I removed all old cauldron/forge jars and libs before copying the new ones over.
