### ISSUE TITLE
[1.7.10] Twilight Forest cause server crash (Missing class)

### ISSUE THREAD

**Issue by ghost** [MinecraftPortCentral/Cauldron-Issues#31]
When use TF 2.3.2 with build 198 server started, works normal. When use ingame item Magic Beans from this mod, server crashes.

If Upgrade to latest build 206, server wont started and crashes due Magic Beans from TF, error is similar like usin item ingame with previous build.

Crashlog:

http://pastebin.com/EphPc0gs

**Comment by bloodmc** [comment]
```
@SideOnly(Side.CLIENT)
public float getCloudHeight()
{
    return this.terrainType.getCloudHeight();
}
```

TF is calling a client method on server. Report to TF dev.

**Comment by ghost** [comment]
Reported, waiting for reply.
