### ISSUE TITLE
Unable to launch with 'finiteWater=true' in CodeChickenCore.cfg

### ISSUE THREAD

**Issue by TheBrain0110** [MinecraftPortCentral/Cauldron-Issues#32]
Setting finiteWater=true in CodeChickenCore.cfg will cause Cauldron to be unable to launch with

java.lang.NoClassDefFoundError: net/minecraft/block/BlockDynamicLiquid

Full log at: https://gist.github.com/TheBrain0110/89fafc62823d8e737d99
cauldron-1.7.10-1.1231.01.207 and CodeChickenCore-1.7.10-1.0.4.29

I've tried on both openjdk 1.7.65 and oracle java 1.8.25, and the Recommended (1.0.2.9) and Latest (1.0.4.29) builds of CodeChickenCore, it's all the same.

**Comment by bloodmc** [comment]
We've had this feature long before CCC did which is why it breaks when you turn it on through CCC. Disable it in CCC and set infiniteWater to false in cauldron.yml
