### ISSUE TITLE
Mail registrations not working on the Cauldron forums

### ISSUE THREAD

**Issue by keenerb** [MinecraftPortCentral/Cauldron-Issues#33]
Nobody is receiving their activation email.  Can this be fixed?  There are a LOT of issues in IRC because of this...

**Comment by bloodmc** [comment]
Use gmail for now.

**Comment by RaptorSB** [comment]
So if we've already signed up with a non-gmail account, are we supposed to create a new account? If this is the case, is there a way to get the user name released?
