### ISSUE TITLE
Terrafirmacraft Player Damage Calculations

### ISSUE THREAD

**Issue by Azaysol** [MinecraftPortCentral/Cauldron-Issues#35]
Hey Blood, have one more issue that was not resolved with TFC. Basically any player inflicted damage by the enviroment is using vanilla damage instead of the recalculated TFC damage.
: fire, drowning and fall damage

Going to quote what ppl said in about it back in issue 15

joserobjr:

I also noticed that explosion and fall damages are taking are too low and is making the player basically invulnerable to that kind of damages.

aleksandrzenin:

As I can see the solution must be simple: you need to calculate damage taken in relative quantities not in absolute ones. When drowning, falling etc. it takes 0.5-3 hp in vanilla healthpoints, but TFC healthbar has 1000 hp by default and max hp can be changed in game by consuming different types of food, level up and etc. So you need to recalculate damage: e.g. drowning taking a half of vanilla heart per act, its equals 0.5/10 = 5% of max heath, then you need to took off 5% of TFC current max health, 5% of 1000, for example, = 50 TFC hp.

still happening with the newest build 

using Cauldron CauldronInstallerPatch-1.1231.01.208
and Terrafirmacraft [1.7.10]TerraFirmaCraft-0.79.9

thanks for your time

**Comment by Azaysol** [comment]
Wanted to note this damage also applies to mobs when the sun comes out they only take 1 damage per tick when they catch on fire

**Comment by bloodmc** [comment]
OK, i'll take a look at it when I get some more time.

**Comment by bloodmc** [comment]
@aldo1028 Fixed bug, will be included in next update.

**Comment by bloodmc** [comment]
Fixed in build 209.
