### ISSUE TITLE
The "Sapling crash"

### ISSUE THREAD

**Issue by sawine** [MinecraftPortCentral/Cauldron-Issues#37]
Hello,

I've been experiencing this crash on the latest 3 Cauldron builds.

Crash log: http://bin.ex.gg/raw/ebosaxanaq

Unfortunately I don't know how to replicate the crash. I tried to teleport to all the locations listed in the crash report but it didn't reproduce the issue.

The crash occurs every now and then, averaging once per 24h.

Thank you for looking into it.

Regards
sawine

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/mcpc-mvn-repo/commit/90905514b9d608ca074ec4f0fc2fa9f5b1fa0e8f

Wipe out your libraries folder and reinstall to get fixed API. It should report version as 1.1231.02.208
