### ISSUE TITLE
`/op USER` no longer works properly?

### ISSUE THREAD

**Issue by ylluminate** [MinecraftPortCentral/Cauldron-Issues#39]
After this last patch, no server users have been able to issue op based commands such as `/gamemode` or such.  Kind of odd because it seems as though it should work since there are no messages within the server console and the `ops.json` file appears to be fine and intact with the same structure as what worked hitherto.

Any ideas if there's anything that could have b0rked permissions from the last update?

**Comment by bloodmc** [comment]
Same issue as before, wrong API.
