### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState

### ISSUE THREAD

**Issue by ylluminate** [MinecraftPortCentral/Cauldron-Issues#40]
Just got a new crash with this most recent build patch while simply idling with one user logged doing nothing: https://gist.github.com/f66e1910bf737d972dfc

**Comment by bloodmc** [comment]
You are using an outdated API. Wipe out your libraries folder and re-run the installer.

**Comment by ylluminate** [comment]
Very interesting @bloodmc.  Is there a suggested shell incantation then to perform at the front of each patch update?  i.e. cd ~/mc; rm -fr libraries/*; #exec_installer jar ?
