### ISSUE TITLE
Server startup issue

### ISSUE THREAD

**Issue by Cr1cket** [MinecraftPortCentral/Cauldron-Issues#42]
I am atttempting to run a Direwolf20 modpack server with cauldron, but I am having issues starting the server. The server does not generate any crash reports or log files, so I have to copy directly from command prompt.

https://gist.github.com/jstuie/2be5c20fb464a6c79940

This does not happen when I run the server without Cauldron

**Comment by bloodmc** [comment]
You either didn't run the installer or deleted/renamed the minecraft server jar.

**Comment by Cr1cket** [comment]
I have ran the installer and both are there. I had aversion from before you started using installers that works fine, so I am using that
