### ISSUE TITLE
Item metadata

### ISSUE THREAD

**Issue by SharkROAR** [MinecraftPortCentral/Cauldron-Issues#43]
Since I updated to version 1.1231.01.208 via patch, item meta data is not being saved.
Every plugin that uses renamed items, item lore, or other data, does not show the respective things anymore. Even player heads do not work properly. Spawning in the head of a player, will just give a default head instead.

Any ideas?

**Comment by devryb** [comment]
This issue is also occuring with the Boss Shop plugin

**Comment by devryb** [comment]
I can confirm this issue started in build 207 and its something to do with the newer library files

**Comment by bloodmc** [comment]
@SharkROAR create a fresh world and reproduce issue. Make sure to list exactly how to reproduce.

**Comment by bloodmc** [comment]
@SharkROAR @devryb Nevermind, I reproduced bug. It will be fixed shortly.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/mcpc-mvn-repo/commit/e902defa8fc60a6ea28235819eaed35c42d7da90

Wipe out your libraries folder and reinstall to get latest API version 04

**Comment by devryb** [comment]
Thank you confirmed fixed

**Comment by SharkROAR** [comment]
Thank you very much
