### ISSUE TITLE
1.7.10 Invisible players doesn't become visible

### ISSUE THREAD

**Issue by tachigami** [MinecraftPortCentral/Cauldron-Issues#46]
Seems like showPlayer() method is broken, Spigot #1649 doesn't have this issue.

**Comment by tachigami** [comment]
UPD: Player becomes visible if he moves on 3-6 blocks in any direction

**Comment by bloodmc** [comment]
@TeroBlaZe Had a bad mapping in CraftPlayer, fix will be in build 211.

**Comment by bloodmc** [comment]
Fixed in build 211.
