### ISSUE TITLE
AMEventHandler.onEntityLiving

### ISSUE THREAD

**Issue by mattymaats** [MinecraftPortCentral/Cauldron-Issues#48]
Hi Blood,

I don't know if this is one you'd be able to look at but I went to the Hardcore ender expansion guys as I thought the issue was with them but they said it looks like Ars Magica is doing something funky and said it should be reported that way but cauldron servers aren't support at all on his end, if you could let me know what you think and if it's not something to do with a cauldron conflict (the issue doesn't seem to occur in single player just when on a server though.)

Crash Report - http://pastebin.com/XiLgQM9n
HEE report - https://github.com/chylex/Hardcore-Ender-Expansion/issues/66#issuecomment-61126007

Running Cauldron 209 update on 1.7.10.

If you need any more information just let me know.
Regards,
Matty

**Comment by bloodmc** [comment]
am2.playerextensions.ExtendedProperties.getMaxMana(ExtendedProperties.java:251)

triggered by 

chylex.hee.entity.mob.EntityMobHomelandEnderman.func_70071_h_(EntityMobHomelandEnderman.java:942)

Looks like a compatibility issue between HEE and am2. If you can reproduce it and confirm it works on Forge servers then i'll reopen ticket.

**Comment by mattymaats** [comment]
Hi Blood,

Thank you so much for getting back to me, it happens on a forge server as well so I'm passing it onto the mod devs but doubtful anything will get fixed if it's on the AM2 side as Mithion has left.
