### ISSUE TITLE
Sender cannot be null - bps patch 209

### ISSUE THREAD

**Issue by Menphis88** [MinecraftPortCentral/Cauldron-Issues#49]
So i still get the issue with not being able to run console commands. 
I just patched .198 with the .209 patch, and the issue was still there.

Complete log:
http://pastebin.com/wtmRNjyv

**Comment by Menphis88** [comment]
Btw, at first, i tried adding the patches one by one. But once i applied .205 successfully, and tried patching .206 i got an error in spigot patcher: http://imgur.com/DD9DBll

So i went ahead and applied .209 to .198 directly, not sure if thats causing the issue.

**Comment by bloodmc** [comment]
Fixed in build 210.
