### ISSUE TITLE
Armor loses durability in god-mode

### ISSUE THREAD

**Issue by zampa00** [MinecraftPortCentral/Cauldron-Issues#5]
If you hit someone who is in god and wears an armor, he takes no damage but the armor loses durability.
Easly replicable with a clean installation and installing essentials (or any other plugin which cancel EntityDamageByEntityEvent).

Tested with cauldron-1.7.10-1.1217.01.205

**Comment by bloodmc** [comment]
OK thanks, I'll look into this issue this weekend.

**Comment by zampa00** [comment]
Any news?

**Comment by LaoTheLizard** [comment]
If you hit someone who is in no-pvp zone of worldguard, you'll get the same effect.

**Comment by LaoTheLizard** [comment]
In single mode 1.7.10 and in all modes earlier (I didn't check craftbukkit) armor losts its durability by 1 point for each hit. Now its 2 to 4 points. With regard to minecraft wiki - all is right. Well then single mode of minecraft has bug? Armor losing its durability too fast, also. One night walk - one diamond set.

**Comment by bloodmc** [comment]
@LaoTheLizard Please see if this bug has been fixed in build 210

**Comment by zampa00** [comment]
Armor still takes damage in god mode in build 210

**Comment by bloodmc** [comment]
@zampa00 @LaoTheLizard Please test build 211

**Comment by zampa00** [comment]
It seems fixed now! I'm in god on a cactus and my armor doesn't take damage as before

**Comment by LaoTheLizard** [comment]
+
Well done. Mark 10. :)

**Comment by bloodmc** [comment]
Fixed in build 211.
