### ISSUE TITLE
[1.7.10 - 209] Startup Error...

### ISSUE THREAD

**Issue by vico93** [MinecraftPortCentral/Cauldron-Issues#50]
Hi all, its a long time since i last played using Cauldron :(
I'm having trouble installing Cauldron patched with the last BPS (1.1231.04.209).

Setup everyright how the manual says times and times, but this still give me this start error:

http://pastebin.com/zSbgicCk

Another things i've tried:
- Putting (and removing) cauldronbukkit to test if was this the cause (cauldronbukkit-versiontrash.jar and simply cauldronbukkit.jar);
- Installing Forge server (same version) at top of Cauldron;

None of these works.

Am i a very noob with this, or the tutorial was unclear or the libraries were screwed up with this bps? 
What i need to do?

**Comment by tachigami** [comment]
It's impossible, try this
http://cauldron.minecraftforge.net/threads/important-how-to-apply-bps-patches.487/

**Comment by vico93** [comment]
I followed this very same tutorial...

**Comment by bloodmc** [comment]
Stop deleting/modifying the minecraft_server.1.7.10.jar

**Comment by vico93** [comment]
Whoa! But i'm not deleting nor modifying the vanilla server jar... any ways i trying get the same error.

**Comment by vico93** [comment]
Oddly, yesterday after that post i re-patched cauldron, run the installer and everything works, even without some libraries!
IMO the trouble was because i ran twice the installer, because i tought could be necessary run the installer again and again until all libraries get downloaded.
Anyway thanks for all! ^^
