### ISSUE TITLE
Anti-Cheat teleports players back to their original location on Cauldron 

### ISSUE THREAD

**Issue by lorenzorota** [MinecraftPortCentral/Cauldron-Issues#51]
Spigot Version: 20140927a (latest)
## Cauldron Version: 1.7.10-1.1231.04.209 (latest)

I created brand new map where I tested the Anti-Cheat plugin on Spigot and a result it worked fine without any issues of being teleported back at attempting to walk.
When I tested the same map/settings on Cauldron it would constantly teleport the player backwards at attempt of walking,jumping or sprinting.

I couldn't find back any trace in either logs of both tests so I presume something in the code structure of Cauldron is limiting the anticheat plugin to work properly.

Could you please look into this bug and try to fix it?
Thank you very much

**Comment by bloodmc** [comment]
Anti cheat plugins are not supported as they are built entirely for vanilla.
