### ISSUE TITLE
 net.minecraft.world.WorldServer [ mt ] with checksum 

### ISSUE THREAD

**Issue by pontusedberg** [MinecraftPortCentral/Cauldron-Issues#52]
Hello i have been trying to get my server to work now for a while but i get thease weird errors the then server just freezes, anyone know the problem?
Fml, COnsole, And logs! :D
http://mibpaste.com/N3TAMC 
http://mibpaste.com/zrFYYI 
http://pastebin.com/0fgf5VFX 

How to replicate!

Get fastcraft aperently and install in your world!
To fix the problem simple remove fast craft and enjoy

**Comment by bloodmc** [comment]
Fastcraft has to add support for Cauldron since they are using ASM injection.
