### ISSUE TITLE
cpw.fml.common.loader.sortmodlist    CRASH

### ISSUE THREAD

**Issue by goldberg012** [MinecraftPortCentral/Cauldron-Issues#56]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11/2/14 4:43 PM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:317)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 83044848 bytes (79 MB) / 636485632 bytes (607 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 2 total; -XX:MaxPermSize=6144m -Xmx6144M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 177 mods loaded, 176 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded
    FML{7.10.25.1207} [Forge Mod Loader](cauldron-server.jar) Unloaded
    Forge{10.13.0.1207} [Minecraft Forge](cauldron-server.jar) Unloaded
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded
    Aroma1997Core{1.0.2.9} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded
    NotEnoughItems{1.0.3.57} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.57-universal.jar) Unloaded
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded
    TubesCore{${version}} [Tubes Core](minecraft.jar) Unloaded
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded
    malisiscore{1.7.10-0.9.6} [Malisis Core](malisiscore-1.7.10-0.9.6.jar) Unloaded
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded
    AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.10.jar) Unloaded
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded
    Aroma1997CoreHelper{1.0.2.9} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded
    Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.2-1.0.2.16.jar) Unloaded
    asielib{0.3.1} [asielib](AsieLib-1.7.10-0.3.1.jar) Unloaded
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded
    bdlib{1.4.5.24} [BD Lib](bdlib-mc1710-1.4.5.24.jar) Unloaded
    betterstorage{0.10.0.112-dev} [BetterStorage](BetterStorage-1.7.10-0.10.1.113.jar) Unloaded
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded
    BiblioWoodsBoP{1.8} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.8].jar) Unloaded
    BiblioWoodsForestry{1.6} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.6].jar) Unloaded
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded
    BigReactors{0.4.0rc10} [Big Reactors](BigReactors-0.4.0rc10.jar) Unloaded
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.992-universal.jar) Unloaded
    AWWayofTime{v1.2.0} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0%281.7.10%29.jar) Unloaded
    Botania{r1.2-129} [Botania](Botania r1.2-129.jar) Unloaded
    BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded
    BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded
    BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded
    BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded
    BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded
    BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded
    CarpentersBlocks{3.3.0} [Carpenter's Blocks](Carpenters Blocks v3.3.0 - MC 1.7.10.jar) Unloaded
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded
    DimensionalAnchors{59.0.2} [Dimensional Anchors](dimensional-anchor-59.0.2.jar) Unloaded
    EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting](EasyCrafting-1.7.10-2.0.1.16.jar) Unloaded
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded
    EnderIO{1.7.10-2.0.8.221} [Ender IO](EnderIO-1.7.10-2.0.8.221.jar) Unloaded
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12b8.jar) Unloaded
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded
    factorization.misc{1.7.10-0.8.88.2} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.2.jar) Unloaded
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.2.jar) Unloaded
    factorization{1.7.10-0.8.88.2} [Factorization](Factorization-1.7.10-0.8.88.2.jar) Unloaded
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded
    gendustry{1.3.4.29} [GenDustry](gendustry-mc1710-1.3.4.29.jar) Unloaded
    advgenerators{0.9.2.15} [Advanced Generators](generators-mc1710-0.9.2.15.jar) Unloaded
    GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) Unloaded
    GregsLighting{1.11.0} [Greg's Lighting](GregsLighting-1.11.0-mc1.7.10.jar) Unloaded
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded
    IC2NuclearControl{1.7.10.08} [Nuclear Control](ic2nc-1.7.10-1.7.10.08.jar) Unloaded
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.0.jar) Unloaded
    ImmibisCore{59.0.1} [Immibis Core](immibis-core-59.0.1.jar) Unloaded
    IC2{2.2.647-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.647-experimental.jar) Unloaded
    InfiniTubes{59.0.1} [InfiniTubes](infinitubes-59.0.1.jar) Unloaded
    inventorytweaks{1.59-dev-153-e32ef23} [Inventory Tweaks](InventoryTweaks-1.59-dev-153.jar) Unloaded
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded
    LiquidXP{59.0.0} [Liquid XP](liquid-xp-59.0.0.jar) Unloaded
    malisisdoors{1.7.10-1.1.3} [Malisis' Doors](malisisdoors-1.7.10-1.1.3.jar) Unloaded
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded
    Mekanism{7.1.1} [Mekanism](Mekanism-1.7.10-7.1.1.113.jar) Unloaded
    MekanismGenerators{7.1.1} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.1.113.jar) Unloaded
    MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.113.jar) Unloaded
    MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System](mffs-4.1.0.31-core.jar) Unloaded
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded
    MineTweaker3{${version}} [MineTweaker 3](MineTweaker3-1.7.10-3.0.7.jar) Unloaded
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded
    Morpheus{1.7.10-1.5.19} [Morpheus](Morpheus-1.7.10-1.5.19.jar) Unloaded
    MSM3{3.0.0d} [More Swords 3](MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) Unloaded
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded
    NEIPlugins{1.1.0.9-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.9-unofficial.jar) Unloaded
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-434.jar) Unloaded
    OpenComputers{1.3.6.69} [OpenComputers](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded
    fodc{1.5.2} [Ore Dictionary Converter](OreDictionaryConverter-1.5.2.jar) Unloaded
    PneumaticCraft{1.2.6} [PneumaticCraft](PneumaticCraft-1.7.10-1.2.9-24-universal.jar) Unloaded
    PowerConverters{1.7.10-3.0.0.27} [Power Converters](PowerConverters-1.7.10-3.0.0.27.jar) Unloaded
    pressure{0.9.5.33} [Pressure Pipes](pressure-mc1710-0.9.5.33.jar) Unloaded
    ProjectE{Alpha 0.2c} [ProjectE](ProjectE-Alpha 0.2c.jar) Unloaded
    ProjRed|Core{4.5.0.50} [ProjectRed](ProjectRed-Base-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Compatibility{4.5.0.50} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Integration{4.5.0.50} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Transmission{4.5.0.50} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Illumination{4.5.0.50} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Expansion{4.5.0.50} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Transportation{4.5.0.50} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.0.50.jar) Unloaded
    ProjRed|Exploration{4.5.0.50} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.0.50.jar) Unloaded
    QuarryPlus{1.7.10-1.5.7.7} [QuarryPlus](QuarryPlus-1.7.10-1.5.7.7.jar) Unloaded
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded
    RandomThings{2.1.5} [Random Things](RandomThings-2.1.5.jar) Unloaded
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded
    RIO{1.4.3} [RemoteIO](RemoteIO-1.7.10-1.4.3.B49-universal.jar) Unloaded
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine](resonant-engine-2.0.0.118-core.jar) Unloaded
    ResonantInduction|Electrical{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Electrical](resonant-induction-0.3.4.116-core.jar) Unloaded
    ResonantInduction|Mechanical{1.0} [Resonant Induction Mechanical](resonant-induction-0.3.4.116-core.jar) Unloaded
    ResonantInductionCore{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction](resonant-induction-0.3.4.116-core.jar) Unloaded
    ResonantInduction|Atomic{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Atomic](resonant-induction-0.3.4.116-core.jar) Unloaded
    ResonantInduction|Archaic{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Archaic](resonant-induction-0.3.4.116-core.jar) Unloaded
    statues{2.1.4} [Statues](statues-1.7.10-2.1.4.jar) Unloaded
    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) Unloaded
    StevesFactoryManager{A92} [Steve's Factory Manager](StevesFactoryManagerA92.jar) Unloaded
    supercraftingframe{1.7.10.1} [Super Crafting Frame](supercraftingframe-1.7.10.1.jar) Unloaded
    Sync{4.0.0} [Sync](Sync-4.0.0.jar) Unloaded
    TConstruct{1.7.10-1.7.1.build748} [Tinkers' Construct](TConstruct-1.7.10-1.7.1.jar) Unloaded
    TF2Dispenser{1.7.10} [TF2 Dispenser](TF2Dispenser-1.7.10.jar) Unloaded
    TF2Sentry{1.7.10} [TF2 Sentry](TF2Sentry-1.7.10.jar) Unloaded
    TF2Teleporter{1.7.10} [TF2 Teleporter](TF2Teleporter-1.7.10.jar) Unloaded
    Thaumcraft{4.2.1.3} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.3.jar) Unloaded
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded
    TMechworks{1.7.10-75.0afb56c} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.9.jar) Unloaded
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded
    Tubes{2.0.4} [Tubes](Tubes-1.7.10-2.0.4.jar) Unloaded
    Tubestuff{59.0.0} [Tubestuff](tubestuff-59.0.0.jar) Unloaded
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded
    UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity](universal-electricity-4.0.0.78-core.jar) Unloaded
    usefulDNS{2.2.8} [usefulDNS](usefulDNSv2.2.8.jar) Unloaded
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded
    wawla{1.0.7} [What Are We Looking At](Wawla-1.0.7_1.7.10.jar) Unloaded
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded
    WR-CBE|Core{1.4.1.4} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.4-universal.jar) Unloaded
    WR-CBE|Addons{1.4.1.4} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.4-universal.jar) Unloaded
    WR-CBE|Logic{1.4.1.4} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.4-universal.jar) Unloaded
    bspkrsCore{6.13} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.13.jar) Unloaded
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded
    ForgeMicroblock{1.1.0.309} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
    ForgeMultipart{1.1.0.309} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
    McMultipart{1.1.0.309} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by bloodmc** [comment]
You are missing a mod, nothing to do with cauldron.

**Comment by goldberg012** [comment]
oh ok ty
