### ISSUE TITLE
Cauldron-TPPI-1.6.4 constant random crash

### ISSUE THREAD

**Issue by ghost** [MinecraftPortCentral/Cauldron-Issues#58]
Hey, im using the 1.6 jar from that maeyanie website for my tppi server, i had the server up for about a week and then randomly we started getting these random crashes, with the only output being a server thread dump, and seeing as i dont really understand what the stuff in it means, I put it on pastebin with the hope that you guys can help me figure this out: http://pastebin.com/5Bfsx7xh

**Comment by bloodmc** [comment]
remove Opis and everything will work fine. Use WarmRoast instead.

**Comment by ghost** [comment]
Ty blood, Btw could you recommend a good wrapper for ubuntu 14.04 if you know any
