### ISSUE TITLE
compatibility jar for mod packs

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [MinecraftPortCentral/Cauldron-Issues#60]
there are currently two types jars that mod packs one ftb jar 1 jar 

crazy craft  has 1 jar not 2 how  how much supposed to run a modpack server that  will not run on 2 minecraft jars  i n the mcpc+ was work fine but now cauldron does not work for me for ftb direwolf20 currently have compatibility issues with cauldron  are there any old MCpc+ download home replacements that run on 1 jar

**Comment by REVIEWGAMINGMAN** [comment]
for 1.6.4

**Comment by REVIEWGAMINGMAN** [comment]
direwolf20 update 1.7.10 hopefully within a year does issues fixed

**Comment by bloodmc** [comment]
This does not make any sense. If you want to use cauldron instead of ftb then just run our jar instead of theirs. More info can be found at cauldron.minecraftforge.net

**Comment by REVIEWGAMINGMAN** [comment]
I am talking about MCpc+ original setup
