### ISSUE TITLE
net/minecraft/world/World$3 Server Crash

### ISSUE THREAD

**Issue by spruill7716** [MinecraftPortCentral/Cauldron-Issues#61]
I really don't know where to start here. Its present even with the latest patch.
https://www.dropbox.com/s/e2v9a8r32iunjz7/crash-2014-11-03_17.18.30-server.txt?dl=0

**Comment by Katelyn-SN** [comment]
This means your missing the minecraft_server.1.7.10.jar which is a required library for cauldron.

**Comment by spruill7716** [comment]
I already have minecraft_server.1.7.10.jar installed.

**Comment by Katelyn-SN** [comment]
Then its not in the same folder as the cauldron jar or is named incorrectly as that is the only way that error can happen.

**Comment by bloodmc** [comment]
Your server ran out of memory which caused the classloader to spit out that error.
