### ISSUE TITLE
Can't create world (MultiWorld, MultiVerse)

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/Cauldron-Issues#7]
hey,

if I try to create a world it allways throws this errors in the console and fails:
http://pastebin.com/dTHS3H7W

(cauldron-1.7.10-1.1207.01.198-server)

**Comment by bloodmc** [comment]
Caused by chickencore

[17:57:02] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[17:57:02] [Server thread/WARN]:        at codechicken.core.CommonUtils.getSaveLocation(CommonUtils.java:21)

**Comment by Chicken-Bones** [comment]
Has been fixed in latest WR-CBE + CCC

**Comment by Sir-Will** [comment]
@Chicken-Bones hm, I already have `CodeChickenCore-1.7.10-1.0.4.29-universal` and `WR-CBE-1.7.10-1.4.1.6-universal`

**Comment by Chicken-Bones** [comment]
I'll need a new log then

**Comment by Sir-Will** [comment]
That's weird. I tried it now again and it worked now somehow.
Thanks.
