### ISSUE TITLE
Tinkers Construct Rapier

### ISSUE THREAD

**Issue by devryb** [MinecraftPortCentral/Cauldron-Issues#71]
When killed by a Rapier from Tinkers Construct on a server with Cauldron your items will immediately despawn.
Tested in singleplayer and the items drop normally.
Both tests were done with an autonomous activator in attack mode.

Using Direwolf20 1.0.1 modpack (Graves disabled) and Cauldron build 209

**Comment by bloodmc** [comment]
@devryb Please test this bps patch and let me know if it fixes this bug

https://www.dropbox.com/s/bip93ysgb0489vs/CauldronInstallerPatch-1.1236.05.211-TEST.bps?dl=0

**Comment by devryb** [comment]
It looks good thanks

**Comment by bloodmc** [comment]
Fixed in build 211.
