### ISSUE TITLE
Opping fake players?

### ISSUE THREAD

**Issue by devryb** [MinecraftPortCentral/Cauldron-Issues#73]
I'm trying to get a Buildcraft Filler to place blocks on a Cauldron server with build 209 (1.7.10)
In the past /op [buildcraft] was all that was required however this doesn't seem to work anymore.
Can someone clarify what needs to be done now?

**Comment by Menphis88** [comment]
Had the same issue.
Go to your cauldron.yml file, in the root of your server files.
On Line 90 theres a section called "fake-players", change: 
"do-login: false"
to
"do-login: true"

And you should be all set :-D

**Comment by devryb** [comment]
No that wasn't it.
It was actually Essentials AntiBuild plugin blocking it.
