### ISSUE TITLE
Entity error and Applied Energistics error

### ISSUE THREAD

**Issue by cauliflower69** [MinecraftPortCentral/Cauldron-Issues#75]
http://www.indeedcommunity.com/hosting/serverlog.txt

It's long but the errors are towards the bottom

**Comment by Xfel** [comment]
Your entity error is identical to #74

**Comment by cauliflower69** [comment]
Any ideas about the Applied Energistics error ?

**Comment by bloodmc** [comment]
Fixed in build 210
