### ISSUE TITLE
Server Crash On Startup

### ISSUE THREAD

**Issue by Redlotus99** [MinecraftPortCentral/Cauldron-Issues#76]
I am not sure this was related to another issue that was submitted, but I wanted to submit mine separate just in case. My pack starts up fine in forge only, but not with Cauldron. I have also updated COFHCore to the latest.

Cauldron 1231

http://pastebin.com/8L5gJ0Vt

**Comment by Redlotus99** [comment]
This was due to fastcraft being installed. I am unsure if it is an error or conflict but when having fastcraft installed the error occurs.

**Comment by bloodmc** [comment]
OK thanks.
