### ISSUE TITLE
Unable to launch java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Twisted-Code** [MinecraftPortCentral/Cauldron-Issues#78]
I just downloaded the installer for the 1.7.10 Cauldron server (from maeyanie's site), ran it, made sure cauldron bukkit (from the same source) was present, and then tried to launch the server with the following batch:

``` bat
java -Xmx1024M -jar cauldron-1.7.10-1.1207.01.198-server.jar
PAUSE
```

it started up and and after a few seconds skipped right to the pause statement... 
logs:
[latest.log](http://pastebin.com/1vnMJFhu)
[fml-server-latest.log](http://pastebin.com/DQwcKTLQ)
[fml-junk-earlystartup.log](http://pastebin.com/ZAVz6W1Y)
System details:
Operating System: Windows 7 Professional, Service Pack 1, 64-bit
...anything relevant I'm forgetting?

**Comment by bloodmc** [comment]
Cauldron-MCPC-Plus-1.7.10-1.1207.01.198

You didn't patch it correctly. Follow the instructions in the Downloads section of our forums at cauldron.minecraftforge.net

**Comment by Twisted-Code** [comment]
Oh 
didn't realize that step was required... >-<
although it isn't always I guess, seeing as the unpatched server ran fine on my laptop (where I initially tried putting humpty dumpty together)

For a minute I thought it  was still broken but then I remembered the EULA
