### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by prodkid** [MinecraftPortCentral/Cauldron-Issues#83]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/13/14 3:22 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:271)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:967)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2673494320 bytes (2549 MB) / 4953997312 bytes (4724 MB) up to 11453595648 bytes (10923 MB)
    JVM Flags: 3 total; -XX:PermSize=256M -XX:MaxPermSize=512M -Xmx12288M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1231 Cauldron-MCPC-Plus vgit-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1231 42 mods loaded, 41 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1231} [Forge Mod Loader](cauldron-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1231} [Minecraft Forge](cauldron-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    act{0.0.2a_1.7.10} [AdminCommandsToolbox](AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.1} [Backpack](backpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterrecords{1.7.10-1.1.6} [Better Records](BetterRecords.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoodsNatura.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.14} [bspkrsCore](bspkrsCore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.0} [Carpenter's Blocks](Carpenters Blocks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{1.5.7} [Chisel](Chisel.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.6.8.1} [CraftGuide](CraftGuide.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10b} [CustomNpcs](CustomNPCs.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    props{1.11} [Decocraft](Decocraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    pixelmon{3.3.3} [Pixelmon](Pixelmon.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extraskins{1.0} [ExtraSkins](ExtraSkins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GTS{1.0.1} [Global Trade System](gts-universal-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.0.0} [iChunUtil](iChunUtil.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Hats{4.0.1} [Hats](Hats.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ivsevs{3.1.0} [IVsEVs](IVsEVs.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_LATL{1.9} [Lamps and Traffic lights](LampsAndTrafficLights.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.3.5} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NBTEdit{1.7.10} [In-game NBTEdit](NBTEdit.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    nbtparty{1} [NBTParty](NBTParty-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    noflyzone{1.0} [No Fly Zone](NoFlyZone-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10b} [Pam's HarvestCraft](PamsHarvestCraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PixelSideCommands{1.0} [PixelCommands](PixelCommands-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_RoadWorks{2.0} [Roadworks](RoadWorks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    safeplace{1.1} [SafePlace](SafePlace-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TallDoors{0.5.1} [Tall Doors Mod](TallDoors.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    tradelogger{1.0} [TradeLogger](TradeLogger-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    trainercommands{1.0.0} [Pixelmon Trainer Commands](TrainerCommands-1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Trapcraft{v2.2.1a} [Trapcraft](Trapcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Treecapitator{1.7.2} [Treecapitator](Treecapitator.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wondertrade{3.1.0} [Wonder Trade](WonderTrade-1.7.10-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extraskinscore{1} [extra skins Core](minecraft.jar) Unloaded->Disabled
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 13 / 200; [EntityPlayerMP['MaxBearCub'/846, l='zenes', x=-257.03, y=58.25, z=455.96](MaxBearCub at -257.0330779094339,58.2531999805212,455.9631000929864), EntityPlayerMP['yodaveth'/938, l='zenes', x=-229.75, y=54.50, z=149.66](yodaveth at -229.75101304475976,54.5,149.66497274607758), EntityPlayerMP['theredwasp'/1364, l='zenes', x=-129.38, y=64.00, z=2659.96](theredwasp at -129.37951893211758,64.0,2659.9644055196263), EntityPlayerMP['harryx66x'/937, l='DIM-1', x=-123.55, y=24.74, z=225.39](harryx66x at -123.55074527939003,24.735840672728273,225.38555616677152), EntityPlayerMP['REAL_DTM'/2198, l='zenes', x=-92.25, y=38.00, z=708.68](REAL_DTM at -92.25433078676,38.0,708.6833517848875), EntityPlayerMP['truephobia'/1288, l='DIM-1', x=-121.05, y=41.25, z=117.30](truephobia at -121.04798150054246,41.24918707874468,117.30000001192093), EntityPlayerMP['shaymond2'/2787, l='zenes', x=-110.75, y=64.00, z=2681.59](shaymond2 at -110.74807729840936,64.0,2681.589855749608), EntityPlayerMP['comet08'/2882, l='zenes', x=1351.52, y=65.00, z=-3651.76](comet08 at 1351.515283966529,65.0,-3651.762499988079), EntityPlayerMP['turtleman1108'/2555, l='zenes', x=-241.91, y=43.92, z=91.04](turtleman1108 at -241.90985553223902,43.92159999847412,91.04344820956209), EntityPlayerMP['zaneart'/3702, l='zenes', x=-159.59, y=50.48, z=203.97](zaneart at -159.58626281862476,50.4807108763317,203.9701498080178), EntityPlayerMP['iHazdawolfe'/3815, l='zenes', x=-1002.75, y=72.00, z=1677.79](iHazdawolfe at -1002.7514294607192,72.0,1677.7852073948552), EntityPlayerMP['DiamondBro1254'/4211, l='zenes', x=-211.50, y=52.18, z=154.50](DiamondBro1254 at -211.5,52.18,154.5), EntityPlayerMP['maxwillem112'/5441, l='zenes', x=-471.70, y=7.65, z=1013.43](maxwillem112 at -471.69999998807907,7.6464000320434575,1013.4250000119209)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Turner17** [comment]
Have you tried turning it on and off again?
