### ISSUE TITLE
Players crashing

### ISSUE THREAD

**Issue by TaliXor** [MinecraftPortCentral/Cauldron-Issues#85]
Players keep crashing on my server every now and then and get the error "Internal Exception: java.io.IOException: Connection reset by peer" This is all the information I have on it, because that is all it shows in console and in logs. Does anyone know what might be causing this issue? I am running the latest Cauldron with  the latest bps patch currently and also have Pixelmon on as well. I highly doubt it is Pixelmon, because no one else has complained about it on the Pixelmon website. if anyone has this same issue or knows a solution to this problem, please reply asap. thank you

**Comment by bloodmc** [comment]
As stated in IRC, this seems like an issue on your end with server. Try another server host to see if problem persists.
