### ISSUE TITLE
Armor taking 4x durability loss under Cauldron vs. forge

### ISSUE THREAD

**Issue by keenerb** [MinecraftPortCentral/Cauldron-Issues#86]
When running Forge 1230, armor takes normal 1x damage.  When running Cauldron, armor takes 4x damage.

Attempting to determine if a specific mod is maybe triggering this bug, but I have over a hundred so it's not particularly quick.

**Comment by LaoTheLizard** [comment]
I confirm this bug. It's critical for pvp and hard difficulty servers.

**Comment by keenerb** [comment]
I can reproduce without any mods installed, albeit it's only 2x durability damage for some reason.

**Comment by bloodmc** [comment]
Please confirm if this has been fixed in build 210

**Comment by bloodmc** [comment]
dupe #72
