### ISSUE TITLE
Compatibility with MineVerseChat bungeecord channels

### ISSUE THREAD

**Issue by aallen42** [MinecraftPortCentral/Cauldron-Issues#9]
After upgrading to CauldronInstallerPatch-1.1217.01.205, channels in the MineVerseChat plugin no longer allow for users to chat in channels in which BungeeCord support is enabled (i.e. forwarding chat messages across the proxy to other servers). 

When trying to send a message, the message simple doesn't send locally or to any other server on the network, indicating an issue with the connection to BungeeCord from cauldron. This issue does not occur on Cauldron B198.

MineVerseChat source: https://github.com/Aust1n46/MineverseChat/

**Comment by bloodmc** [comment]
Ah, it seems my patch that fixed this was lost when i released the bps version. Should be fixed shortly.

**Comment by bloodmc** [comment]
Fixed in build 206.
