### ISSUE TITLE
Patched Cauldron Installer Download issue when running jar

### ISSUE THREAD

**Issue by alicheek** [MinecraftPortCentral/Cauldron-Issues#90]
Issue when trying to use the patched installer for the latest cauldron 1.7.10 jar

link to the issue is here : http://cauldron.minecraftforge.net/threads/cauldroninstallerpatch-1-1231-04-209.581/page-2#post-3631

**Comment by bloodmc** [comment]
You may see some failed libraries when running the installer from command line, just ignore them.
