### ISSUE TITLE
Issue With Direwolf20 1.7.10 1.0.2

### ISSUE THREAD

**Issue by micmou** [MinecraftPortCentral/Cauldron-Issues#92]
I have recently decided to update our server to the 1.0.2 update of the Direwolf20 pack and having some issues in my Test and Configuration Server it is currently running the latest Cauldron Patch
1236.5.211 we recently updated to this version
the Direwolf20 Server Runs Forge 1231

the latest Forge log With Cauldron
http://pastebin.com/bamb6ZJn

Would not let me put on pastebin so here is my dropbox folder with the logs for theirs and the mods and configs I have no plugins loaded at all and followed the tutorial on how to install a cauldron server. It only happens when I install the Direwolf20 1.7 1.0.2 mods into cauldron there server version works just fine.

https://www.dropbox.com/sh/1yy7etjqjavp6uj/AACyQgMcJJsC03PfdbzYyAVpa?dl=0

In case that link doesn't work here is the mediafire link 
http://www.mediafire.com/download/u4hg54kn5e8pd3p/Cauldron_and_Dire.zip

Just tried it with the latest 1231.4.209 Cauldron and it is the same as with 1236
http://pastebin.com/w8kPt5nb

**Comment by tyler2k15** [comment]
I have run into this same issue. Will there be a fix soon for this?

**Comment by jules103** [comment]
When you remove CoFH it works(or put in the old version), just found this after i posted my own report.
The new versions of CoFH are not supported somehow.

**Comment by bloodmc** [comment]
After speaking with CoFH devs, this issue was fixed in latest B8 build. Update and it should work.

**Comment by jules103** [comment]
Thanks Super cool!
