### ISSUE TITLE
Hardcore Ender Expansion Worldgen Crash

### ISSUE THREAD

**Issue by tgarr0** [MinecraftPortCentral/Cauldron-Issues#94]
Cauldron Version: 1.7.10-1.1236.05.211
Hardcore Ender Expansion Version: 1.7.10  v1.6.5

When generating new chunks in the End, errors will occur, and the player causing the generation will be kicked.  Rejoining (or more specifically reentering the End) after these errors triggers a server crash.  These problems were introduced with changes made to HEE's worldgen since its previous release (2014-10-12).

Server Log: http://pastebin.com/WRZfbDgT
Server Crash Log: http://pastebin.com/eiztqpCv
HEE's Repository: https://github.com/chylex/Hardcore-Ender-Expansion

**Comment by bloodmc** [comment]
@tgarr0 Did you test Forge?

**Comment by tgarr0** [comment]
Nothing went wrong while testing with a Forge-only server, and I haven't seen any other reports of worldgen crashes (with or without Cauldron).

**Comment by tgarr0** [comment]
I may have been premature in thinking that this was a Cauldron-related problem.  While the worldgen crash happens far more frequently with Cauldron, I was (eventually) able to get a crash with just a Forge (1232) server.  The difference in frequency and immediate crashing seem a bit odd, but this issue can probably be closed or frozen until after changes are made on HEE's end.
Issue on HEE's GitHub: https://github.com/chylex/Hardcore-Ender-Expansion/issues/79

**Comment by tgarr0** [comment]
Changes made in HEE to compensate for worldgen errors appear to be just as effective on a Cauldron server.
