### ISSUE TITLE
cauldron/bungeecord crashing client to desktop

### ISSUE THREAD

**Issue by nightstalker6669** [MinecraftPortCentral/Cauldron-Issues#95]
i seem to be having a problem where when i log in thru the bungeecord server to a second world created thru multiverse on a cauldron server i get this error, http://pastebin.com/cpFETxRd , the bungeecord console throws this error on client disconnect http://pastebin.com/it1Cy923 . i'm using bungeecord build #1018, cauldron 1236.05.211.

**Comment by keenerb** [comment]
I also see this error, and I'm not using Bungee.  When I use warpbook to teleport to one of my Bukkit dimensions I get this following error:

After that, I can re-log and everything will work fine.

http://pastie.org/9729132

**Comment by bloodmc** [comment]
dupe #4
