### ISSUE TITLE
Buildcraft quarry not bracking blocks

### ISSUE THREAD

**Issue by ghosty1911** [MinecraftPortCentral/Cauldron-Issues#99]
I am not sure it´s a problem from Buildcraft ore Minecraft-Cauldron.
I run a Cauldron-servern (forge version 1236) an the quarry starts to work but it don´t brack the blocks but when i drop an item in front of the minertop it will be take.
In Singleplayer it works fine

I use the Buildcraft version 6.1.8 from the Buildcraft side but have test it with the latest build to

**Comment by ghost** [comment]
Did you tried running it on a cauldron without plugins?
There are some plugins that cause that issue if they are not configured.

**Comment by ghosty1911** [comment]
i have test, it´s a plugin issue so can be closed
